# Header
menu:
  Home: /
  Games: /portfolio
  Blog Archives: /archives

# Content
excerpt_link: More
prev: Prev
next: Next
reply: Reply
share: Share
fancybox: true
subtitle: Have a seat, right over there.
do_share: false

# Sidebar
widgets:
- search
- music
- category
- recent_posts
- tag
- tagcloud

# Miscellaneous
google_analytics:
duoshuo_shortname: 
rss: 
google_site_verification: 
baidu_site_verification: 
favicon: 
music: 